# -*- coding: utf-8 -*-
"""Tourbuddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1831egkAtLx6cG_vdGwNcL4gvTVDnOqqR
"""

import pandas as pd

# Load the datasets
region_df = pd.read_excel('/content/Region.xlsx')
country_df = pd.read_excel('/content/Country.xlsx')
continent_df = pd.read_excel('/content/Continent.xlsx')
item_df = pd.read_excel('/content/Item.xlsx')
updated_item_df = pd.read_excel('/content/Updated_Item.xlsx')
city_df = pd.read_excel('/content/City.xlsx')
transaction_df = pd.read_excel('/content/Transaction.xlsx')
user_df = pd.read_excel('/content/User.xlsx')
mode_df = pd.read_excel('/content/Mode.xlsx')
type_df = pd.read_excel('/content/Type.xlsx')

print("All datasets loaded successfully.")

print("\n--- Transaction DataFrame Info ---")
display(transaction_df.head())
print(transaction_df.info())

print("\n--- User DataFrame Info ---")
display(user_df.head())
print(user_df.info())

print("\n--- City DataFrame Info ---")
display(city_df.head())
print(city_df.info())

# Handling missing values in Transaction DataFrame
# For 'VisitMode', we might infer or replace with a default/unknown if necessary.
# For numerical columns like 'Rating', we can fill with mean/median or 0 if it means 'no rating'.
# Let's start by looking at missing values percentage for each column

print("\nMissing values before handling:")
print(transaction_df.isnull().sum() / len(transaction_df) * 100)

# Filling 'VisitMode' with a placeholder for now, assuming it might be categorical and missing means 'not specified'
transaction_df['VisitMode'].fillna(0, inplace=True) # Assuming 0 can represent 'unknown mode'

# Fill 'Rating' with the median, as ratings can be skewed.
transaction_df['Rating'].fillna(transaction_df['Rating'].median(), inplace=True)

print("\nMissing values in Transaction DataFrame after handling:")
print(transaction_df.isnull().sum())
display(transaction_df.head())

# Handling missing values in User DataFrame
print("\nMissing values in User DataFrame before handling:")
print(user_df.isnull().sum() / len(user_df) * 100)

# For 'CityId' which has missing values, we can fill with the mode or a placeholder.
user_df['CityId'].fillna(user_df['CityId'].mode()[0], inplace=True)

print("\nMissing values in User DataFrame after handling:")
print(user_df.isnull().sum())
display(user_df.head())

# Handling missing values in City DataFrame
print("\nMissing values in City DataFrame before handling:")
print(city_df.isnull().sum() / len(city_df) * 100)

# Assuming 'CountryId' is a foreign key and should not be null, if they are, it's an integrity issue.
# For this task, we will fill them with a placeholder like 0 or the mode, if appropriate.
city_df['CountryId'].fillna(0, inplace=True) # Placeholder for missing country ID

# For 'CityName', if missing, we can fill with 'Unknown'
city_df['CityName'].fillna('Unknown', inplace=True)

print("\nMissing values in City DataFrame after handling:")
print(city_df.isnull().sum())
display(city_df.head())

"""### Resolving Discrepancies in Categorical Variables

Next, let's address discrepancies in categorical variables like city names, `visit mode`, and `attraction typeid`. This usually involves standardizing spellings, cases, or merging similar categories. Since `VisitMode` and `AttractionTypeId` are already numerical IDs in their respective dataframes, we will check their corresponding lookup tables (`mode_df` and `type_df`) for consistency. For city names, we'll check for variations.

"""

# Standardize city names in city_df
city_df['CityName'] = city_df['CityName'].str.strip().str.title()
print("Unique city names after standardization:")
print(city_df['CityName'].unique())

# Check for discrepancies in 'VisitMode' and 'AttractionTypeId' by looking at their unique values and comparing with lookup tables
print("\nUnique VisitMode in Transaction DataFrame:", transaction_df['VisitMode'].unique())
print("Unique VisitModeId in Mode DataFrame:", mode_df['VisitModeId'].unique())

# Note: transaction_df does not have a 'Type_id' column directly, it has 'AttractionId'.
# If 'attraction typeid' refers to the type from 'item_df' or 'type_df', a merge would be needed.
# For now, we will check 'AttractionTypeId' in the item_df if that is the intent.

# Assuming that `Type_id` in the original prompt referred to `AttractionTypeId` from a related dataframe,
# and `transaction_df` only contains `AttractionId`, we won't directly check `Type_id` in `transaction_df`.
# The discrepancy check for `Type_id` is more relevant to `item_df` or if `AttractionTypeId` was merged into `transaction_df`.
# We will check `AttractionTypeId` unique values from `item_df` against `type_df`.
print("\nUnique AttractionTypeId in Item DataFrame:", item_df['AttractionTypeId'].unique())
print("Unique AttractionTypeId in Type DataFrame:", type_df['AttractionTypeId'].unique())

# If there are VisitMode/AttractionTypeId values in transaction_df/item_df that are not in mode_df/type_df, they are discrepancies.
# For now, we filled missing values with 0, so we should ensure 0 is handled appropriately if it's not a valid ID.
# If 0 is not a valid ID, we can convert it to NaN or a dedicated 'Unknown' category.

# For this example, let's assume 0 was a valid placeholder for 'unknown' and won't cause issues.

"""### Standardize Date and Time Format

Let's standardize the date and time format in the `Transaction` dataset. The `Trans_date` column appears to be an object type, so we need to convert it to datetime objects.
"""

print("Original Transaction DataFrame columns:", transaction_df.columns)

# Create a 'Trans_date' column from 'VisitYear' and 'VisitMonth'
transaction_df['Trans_date'] = pd.to_datetime(transaction_df['VisitYear'].astype(str) + '-' + transaction_df['VisitMonth'].astype(str), format='%Y-%m', errors='coerce')

print("Data type of 'Trans_date' after conversion:", transaction_df['Trans_date'].dtype)

# Check for any dates that failed to parse (will be NaT - Not a Time)
print("Number of unparseable dates:", transaction_df['Trans_date'].isnull().sum())

# If there are unparseable dates, we might need to decide how to handle them (e.g., drop rows, fill with a default date).
# For now, we will leave them as NaT and address if they cause issues later.
display(transaction_df.head())

"""### Handling Outliers or Incorrect Entries

Finally, let's handle outliers or incorrect entries, specifically focusing on the `Rating` column in the `Transaction` dataset. We'll use simple outlier detection methods like checking values outside a reasonable range. The `user_df` does not contain an 'Age' column, so we will not apply outlier handling for age here.
"""

# Handling outliers in 'Rating' column of Transaction DataFrame (assuming rating is typically 1-5 or 1-10)

print("Rating distribution before outlier handling:")
print(transaction_df['Rating'].describe())

# Assume a valid rating range is between 1 and 5 (or 1 and 10, depending on context). Let's assume 1-5 for now.
# Any rating outside this range can be considered an outlier or incorrect entry.
# For this example, let's cap ratings at 5 and set a minimum of 1.

transaction_df['Rating'] = transaction_df['Rating'].clip(lower=1, upper=5)

print("\nRating distribution after outlier handling:")
print(transaction_df['Rating'].describe())
display(transaction_df.head())

"""All specified data preprocessing steps have been performed. The datasets are now cleaner and more consistent for further analysis."""

print("\n--- Transaction DataFrame Info ---")
display(transaction_df.head())
print(transaction_df.info())

print("\n--- User DataFrame Info ---")
display(user_df.head())
print(user_df.info())

print("\n--- City DataFrame Info ---")
display(city_df.head())
print(city_df.info())

# Handling missing values in Transaction DataFrame
# For 'VisitMode', we might infer or replace with a default/unknown if necessary.
# For numerical columns like 'Rating', we can fill with mean/median or 0 if it means 'no rating'.
# Let's start by looking at missing values percentage for each column

print("\nMissing values before handling:")
print(transaction_df.isnull().sum() / len(transaction_df) * 100)

# Filling 'VisitMode' with a placeholder for now, assuming it might be categorical and missing means 'not specified'
transaction_df['VisitMode'].fillna(0, inplace=True) # Assuming 0 can represent 'unknown mode'

# Fill 'Rating' with the median, as ratings can be skewed.
transaction_df['Rating'].fillna(transaction_df['Rating'].median(), inplace=True)

print("\nMissing values in Transaction DataFrame after handling:")
print(transaction_df.isnull().sum())
display(transaction_df.head())

# Handling missing values in User DataFrame
print("\nMissing values in User DataFrame before handling:")
print(user_df.isnull().sum() / len(user_df) * 100)

# For 'CityId' which has missing values, we can fill with the mode or a placeholder.
user_df['CityId'].fillna(user_df['CityId'].mode()[0], inplace=True)

print("\nMissing values in User DataFrame after handling:")
print(user_df.isnull().sum())
display(user_df.head())

# Handling missing values in City DataFrame
print("\nMissing values in City DataFrame before handling:")
print(city_df.isnull().sum() / len(city_df) * 100)

# Assuming 'CountryId' is a foreign key and should not be null, if they are, it's an integrity issue.
# For this task, we will fill them with a placeholder like 0 or the mode, if appropriate.
city_df['CountryId'].fillna(0, inplace=True) # Placeholder for missing country ID

# For 'CityName', if missing, we can fill with 'Unknown'
city_df['CityName'].fillna('Unknown', inplace=True)

print("\nMissing values in City DataFrame after handling:")
print(city_df.isnull().sum())
display(city_df.head())

"""### Resolving Discrepancies in Categorical Variables

Next, let's address discrepancies in categorical variables like city names, `visit mode`, and `attraction typeid`. This usually involves standardizing spellings, cases, or merging similar categories. Since `Mode_id` and `Type_id` are already numerical IDs, we will check their corresponding lookup tables (`mode_df` and `type_df`) for consistency. For city names, we'll check for variations.

"""

# Standardize city names in city_df
city_df['CityName'] = city_df['CityName'].str.strip().str.title()
print("Unique city names after standardization:")
print(city_df['CityName'].unique())

# Check for discrepancies in 'VisitMode' and 'AttractionTypeId' by looking at their unique values and comparing with lookup tables
print("\nUnique VisitMode in Transaction DataFrame:", transaction_df['VisitMode'].unique())
print("Unique VisitModeId in Mode DataFrame:", mode_df['VisitModeId'].unique())

# Note: transaction_df does not have a 'Type_id' column directly, it has 'AttractionId'.
# If 'attraction typeid' refers to the type from 'item_df' or 'type_df', a merge would be needed.
# For now, we will check 'AttractionTypeId' in the item_df if that is the intent.

# Assuming that `Type_id` in the original prompt referred to `AttractionTypeId` from a related dataframe,
# and `transaction_df` only contains `AttractionId`, we won't directly check `Type_id` in `transaction_df`.
# The discrepancy check for `Type_id` is more relevant to `item_df` or if `AttractionTypeId` was merged into `transaction_df`.
# We will check `AttractionTypeId` unique values from `item_df` against `type_df`.
print("\nUnique AttractionTypeId in Item DataFrame:", item_df['AttractionTypeId'].unique())
print("Unique AttractionTypeId in Type DataFrame:", type_df['AttractionTypeId'].unique())

# If there are VisitMode/AttractionTypeId values in transaction_df/item_df that are not in mode_df/type_df, they are discrepancies.
# For now, we filled missing values with 0, so we should ensure 0 is handled appropriately if it's not a valid ID.
# If 0 is not a valid ID, we can convert it to NaN or a dedicated 'Unknown' category.

# For this example, let's assume 0 was a valid placeholder for 'unknown' and won't cause issues.

"""### Standardize Date and Time Format

Let's standardize the date and time format in the `Transaction` dataset. The `Trans_date` column appears to be an object type, so we need to convert it to datetime objects.
"""

print("Original Transaction DataFrame columns:", transaction_df.columns)

# Create a 'Trans_date' column from 'VisitYear' and 'VisitMonth'
transaction_df['Trans_date'] = pd.to_datetime(transaction_df['VisitYear'].astype(str) + '-' + transaction_df['VisitMonth'].astype(str), format='%Y-%m', errors='coerce')

print("Data type of 'Trans_date' after conversion:", transaction_df['Trans_date'].dtype)

# Check for any dates that failed to parse (will be NaT - Not a Time)
print("Number of unparseable dates:", transaction_df['Trans_date'].isnull().sum())

# If there are unparseable dates, we might need to decide how to handle them (e.g., drop rows, fill with a default date).
# For now, we will leave them as NaT and address if they cause issues later.
display(transaction_df.head())

"""### Handling Outliers or Incorrect Entries

Finally, let's handle outliers or incorrect entries, specifically focusing on the `Rating` column in the `Transaction` dataset and `Age` in the `User` dataset. We'll use simple outlier detection methods like checking values outside a reasonable range.
"""

# Handling outliers in 'Rating' column of Transaction DataFrame (assuming rating is typically 1-5 or 1-10)

print("Rating distribution before outlier handling:")
print(transaction_df['Rating'].describe())

# Assume a valid rating range is between 1 and 5 (or 1 and 10, depending on context). Let's assume 1-5 for now.
# Any rating outside this range can be considered an outlier or incorrect entry.
# For this example, let's cap ratings at 5 and set a minimum of 1.

transaction_df['Rating'] = transaction_df['Rating'].clip(lower=1, upper=5)

print("\nRating distribution after outlier handling:")
print(transaction_df['Rating'].describe())
display(transaction_df.head())

"""All specified data preprocessing steps have been performed. The datasets are now cleaner and more consistent for further analysis.

### Initial Data Inspection

Before proceeding with cleaning, let's inspect the first few rows and check for basic information like data types and non-null counts for `Transaction`, `User`, and `City` dataframes.
"""

print("\n--- Transaction DataFrame Info ---")
display(transaction_df.head())
print(transaction_df.info())

print("\n--- User DataFrame Info ---")
display(user_df.head())
print(user_df.info())

print("\n--- City DataFrame Info ---")
display(city_df.head())
print(city_df.info())

"""### Data Cleaning: Handling Missing Values

Now, let's address missing values in the `Transaction`, `User`, and `City` datasets. I will use appropriate strategies for each column based on its type and context.
"""

import pandas as pd

# Handling missing values in Transaction DataFrame
# For 'VisitMode', we might infer or replace with a default/unknown if necessary.
# For numerical columns like 'Rating', we can fill with mean/median or 0 if it means 'no rating'.
# Let's start by looking at missing values percentage for each column

print("\nMissing values before handling:")
print(transaction_df.isnull().sum() / len(transaction_df) * 100)

# Filling 'VisitMode' with a placeholder for now, assuming it might be categorical and missing means 'not specified'
transaction_df['VisitMode'] = transaction_df['VisitMode'].fillna(0) # Assuming 0 can represent 'unknown mode'

# Fill 'Rating' with the median, as ratings can be skewed.
transaction_df['Rating'] = transaction_df['Rating'].fillna(transaction_df['Rating'].median())

print("\nMissing values in Transaction DataFrame after handling:")
print(transaction_df.isnull().sum())
display(transaction_df.head())

# Handling missing values in User DataFrame
print("\nMissing values in User DataFrame before handling:")
print(user_df.isnull().sum() / len(user_df) * 100)

# Based on user_df structure, 'Gender' and 'Age' columns do not exist.
# Missing values for 'CityId' are handled in cell 25d99583.

print("\nMissing values in User DataFrame after handling:")
print(user_df.isnull().sum())
display(user_df.head())

# Handling missing values in City DataFrame
print("\nMissing values in City DataFrame before handling:")
print(city_df.isnull().sum() / len(city_df) * 100)

# Assuming 'CountryId' is a foreign key and should not be null, if they are, it's an integrity issue.
# For this task, we will fill them with a placeholder like 0 or the mode, if appropriate.
# However, it's better to investigate these relationships if this was a full database task.
city_df['CountryId'] = city_df['CountryId'].fillna(0) # Placeholder for missing country ID

# The 'Region_id' column does not exist in city_df, so handling for it is removed.

# For 'CityName', if missing, we can fill with 'Unknown'. Checking for its presence before handling.
if 'CityName' in city_df.columns:
    city_df['CityName'] = city_df['CityName'].fillna('Unknown')

print("\nMissing values in City DataFrame after handling:")
print(city_df.isnull().sum())
display(city_df.head())

"""### Resolving Discrepancies in Categorical Variables

Next, let's address discrepancies in categorical variables like city names, `visit mode`, and `attraction typeid`. This usually involves standardizing spellings, cases, or merging similar categories. Since `Mode_id` and `Type_id` are already numerical IDs, we will check their corresponding lookup tables (`mode_df` and `type_df`) for consistency. For city names, we'll check for variations.

"""

# Standardize city names in city_df
city_df['CityName'] = city_df['CityName'].str.strip().str.title()
print("Unique city names after standardization:")
print(city_df['CityName'].unique())

# Check for discrepancies in 'VisitMode' and 'AttractionTypeId' by looking at their unique values and comparing with lookup tables
print("\nUnique VisitMode in Transaction DataFrame:", transaction_df['VisitMode'].unique())
print("Unique VisitModeId in Mode DataFrame:", mode_df['VisitModeId'].unique())

print("\nUnique AttractionTypeId in Item DataFrame:", item_df['AttractionTypeId'].unique())
print("Unique AttractionTypeId in Type DataFrame:", type_df['AttractionTypeId'].unique())

# If there are VisitMode/AttractionTypeId values in transaction_df/item_df that are not in mode_df/type_df, they are discrepancies.
# For now, we filled missing values with 0, so we should ensure 0 is handled appropriately if it's not a valid ID.
# If 0 is not a valid ID, we can convert it to NaN or a dedicated 'Unknown' category.

# For this example, let's assume 0 was a valid placeholder for 'unknown' and won't cause issues.

"""### Standardize Date and Time Format

Let's standardize the date and time format in the `Transaction` dataset. The `Trans_date` column appears to be an object type, so we need to convert it to datetime objects.
"""

print("Data type of 'Trans_date' before conversion:", transaction_df['Trans_date'].dtype)

# Convert 'Trans_date' to datetime objects
transaction_df['Trans_date'] = pd.to_datetime(transaction_df['Trans_date'], errors='coerce')

print("Data type of 'Trans_date' after conversion:", transaction_df['Trans_date'].dtype)

# Check for any dates that failed to parse (will be NaT - Not a Time)
print("Number of unparseable dates:", transaction_df['Trans_date'].isnull().sum())

# If there are unparseable dates, we might need to decide how to handle them (e.g., drop rows, fill with a default date).
# For now, we will leave them as NaT and address if they cause issues later.
display(transaction_df.head())

"""### Handling Outliers or Incorrect Entries

Finally, let's handle outliers or incorrect entries, specifically focusing on the `Rating` column in the `Transaction` dataset and `Age` in the `User` dataset. We'll use simple outlier detection methods like checking values outside a reasonable range.
"""

# Handling outliers in 'Rating' column of Transaction DataFrame (assuming rating is typically 1-5 or 1-10)

print("Rating distribution before outlier handling:")
print(transaction_df['Rating'].describe())

# Assume a valid rating range is between 1 and 5 (or 1 and 10, depending on context). Let's assume 1-5 for now.
# Any rating outside this range can be considered an outlier or incorrect entry.
# For this example, let's cap ratings at 5 and set a minimum of 1.

transaction_df['Rating'] = transaction_df['Rating'].clip(lower=1, upper=5)

print("\nRating distribution after outlier handling:")
print(transaction_df['Rating'].describe())
display(transaction_df.head())

# The 'Age' column does not exist in user_df, so outlier handling for 'Age' is removed.

"""### Feature Engineering: Data Consolidation

First, let's consolidate all relevant data into a single DataFrame. This involves merging `transaction_df` with `user_df`, `item_df`, `city_df`, `country_df`, `region_df`, `continent_df`, `mode_df`, and `type_df`.
"""

# Rename ID columns in user_df to avoid conflicts later and make merge keys explicit
user_df_renamed = user_df.rename(columns={
    'ContinentId': 'UserContinentId',
    'RegionId': 'UserRegionId',
    'CountryId': 'UserCountryId',
    'CityId': 'UserCityId'
})

# Merge transaction_df with user_df_renamed
consolidated_df = pd.merge(transaction_df, user_df_renamed, on='UserId', how='left')

# Merge with item_df to get attraction details
consolidated_df = pd.merge(consolidated_df, item_df, on='AttractionId', how='left')

# Merge with type_df to get attraction type names
# `type_df` has 'AttractionTypeId' (int64) and 'AttractionType' (object)
# `consolidated_df` already has 'AttractionTypeId' (int64) from item_df
consolidated_df = pd.merge(consolidated_df, type_df, on='AttractionTypeId', how='left')

# Prepare mode_df for merge: select VisitModeId and rename VisitMode to VisitModeName
mode_for_merge = mode_df[['VisitModeId', 'VisitMode']].copy()
mode_for_merge.rename(columns={'VisitMode': 'VisitModeName'}, inplace=True)

# Merge with mode_for_merge to get visit mode names
consolidated_df = pd.merge(consolidated_df, mode_for_merge,
                           left_on='VisitMode', right_on='VisitModeId', how='left')
consolidated_df.drop(columns=['VisitModeId'], inplace=True) # Drop the redundant ID

# Prepare city_df for merge
city_for_merge = city_df[['CityId', 'CityName', 'CountryId']].copy()
city_for_merge.rename(columns={'CityId': 'City_ID', 'CityName': 'City_Name', 'CountryId': 'CityCountryId'}, inplace=True)

# Merge with city_for_merge to get city details
consolidated_df = pd.merge(consolidated_df, city_for_merge,
                           left_on='UserCityId', right_on='City_ID', how='left')
consolidated_df.drop(columns=['City_ID'], inplace=True)

# Prepare country_df for merge
country_for_merge = country_df[['CountryId', 'Country', 'RegionId']].copy()
country_for_merge.rename(columns={'CountryId': 'Country_ID', 'Country': 'Country_Name', 'RegionId': 'CountryRegionId'}, inplace=True)

# Merge with country_for_merge to get country details
consolidated_df = pd.merge(consolidated_df, country_for_merge,
                           left_on='CityCountryId', right_on='Country_ID', how='left')
consolidated_df.drop(columns=['Country_ID'], inplace=True)

# Prepare region_df for merge
region_for_merge = region_df[['RegionId', 'Region', 'ContinentId']].copy()
region_for_merge.rename(columns={'RegionId': 'Region_ID', 'Region': 'Region_Name', 'ContinentId': 'RegionContinentId'}, inplace=True)

# Merge with region_for_merge to get region details
consolidated_df = pd.merge(consolidated_df, region_for_merge,
                           left_on='CountryRegionId', right_on='Region_ID', how='left')
consolidated_df.drop(columns=['Region_ID'], inplace=True)

# Prepare continent_df for merge
continent_for_merge = continent_df[['ContinentId', 'Continent']].copy()
continent_for_merge.rename(columns={'ContinentId': 'Continent_ID', 'Continent': 'Continent_Name'}, inplace=True)

# Merge with continent_for_merge to get continent details
consolidated_df = pd.merge(consolidated_df, continent_for_merge,
                           left_on='RegionContinentId', right_on='Continent_ID', how='left')
consolidated_df.drop(columns=['Continent_ID'], inplace=True)

print("Consolidated DataFrame created. Displaying head and info:")
display(consolidated_df.head())
print(consolidated_df.info())

"""### Feature Engineering: Encoding Categorical Variables

Now that we have a consolidated dataset, let's encode the categorical variables. We'll use one-hot encoding for string-based categorical columns like `VisitMode_mode`, `AttractionType`, `CityName`, `Country`, `Region`, and `Continent`.
"""

# Identify categorical columns to encode
categorical_cols = [
    'VisitModeName', # From mode_df, renamed
    'AttractionType', # From type_df
    'City_Name',  # From city_df, renamed
    'Country_Name', # From country_df, renamed
    'Region_Name', # From region_df, renamed
    'Continent_Name' # From continent_df, renamed
]

# Perform one-hot encoding
consolidated_df_encoded = pd.get_dummies(consolidated_df, columns=categorical_cols, drop_first=True)

print("Categorical variables encoded. Displaying head and info of the new DataFrame:")
display(consolidated_df_encoded.head())
print(consolidated_df_encoded.info())

"""### Feature Engineering: Aggregating User-level Features

Next, we'll aggregate user-level features to create a profile for each user, such as their average rating across different visit modes. We'll add these new features back to the consolidated DataFrame.
"""

# Calculate average rating for each user
user_avg_rating = consolidated_df.groupby('UserId')['Rating'].mean().reset_index(name='User_Avg_Rating')

# Calculate average rating per visit mode for each user
# This creates a pivot table where each row is a user, and columns are avg ratings for each visit mode
user_avg_rating_by_mode = consolidated_df.groupby(['UserId', 'VisitModeName'])['Rating'].mean().unstack(fill_value=0) # Corrected column name
user_avg_rating_by_mode.columns = [f'User_Avg_Rating_Mode_{col}' for col in user_avg_rating_by_mode.columns]
user_avg_rating_by_mode = user_avg_rating_by_mode.reset_index()

# Merge these aggregated features back into the encoded DataFrame
consolidated_df_encoded = pd.merge(consolidated_df_encoded, user_avg_rating, on='UserId', how='left')
consolidated_df_encoded = pd.merge(consolidated_df_encoded, user_avg_rating_by_mode, on='UserId', how='left')

print("User-level features aggregated and merged. Displaying head:")
display(consolidated_df_encoded.head())

"""### Feature Engineering: Normalization

Finally, we'll scale numerical features to ensure better model convergence. We'll use `MinMaxScaler` for features like `Rating`, `VisitYear`, `VisitMonth`, and any other numerical features that might benefit from scaling.
"""

from sklearn.preprocessing import MinMaxScaler

# Identify numerical columns for scaling. Exclude IDs and already encoded categorical columns.
# Also exclude boolean columns created by get_dummies and the original 'Rating' as we'll use the aggregated one.

numerical_cols_to_scale = [
    'VisitYear',
    'VisitMonth',
    'AttractionCityId',
    'AttractionTypeId',
    'User_Avg_Rating'
]

# Add aggregated user ratings by mode, if they exist
for col in consolidated_df_encoded.columns:
    if col.startswith('User_Avg_Rating_Mode_') and col not in numerical_cols_to_scale:
        numerical_cols_to_scale.append(col)

# Also scale the original 'Rating' if it's still present and desired to be scaled directly for model input
if 'Rating' in consolidated_df_encoded.columns and 'Rating' not in numerical_cols_to_scale:
    numerical_cols_to_scale.append('Rating')

# Filter out columns that might not exist after previous steps
numerical_cols_to_scale = [col for col in numerical_cols_to_scale if col in consolidated_df_encoded.columns]

print(f"Numerical columns selected for scaling: {numerical_cols_to_scale}")

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Apply scaling to the selected numerical columns
consolidated_df_encoded[numerical_cols_to_scale] = scaler.fit_transform(consolidated_df_encoded[numerical_cols_to_scale])

print("Numerical features scaled. Displaying head of the final processed DataFrame:")
display(consolidated_df_encoded.head())
print(consolidated_df_encoded.info())

"""### Exploratory Data Analysis (EDA)

#### User Distribution across Continents, Countries, and Regions

### Model Training: Predicting VisitMode (Classification)

Now, let's train a classification model to predict `VisitMode` based on user and transaction features. We will use the `consolidated_df_encoded` DataFrame.
"""

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Define features (X_clf) and target (y_clf) for classification
# The target is 'VisitMode'
# Features will exclude 'VisitMode' and other identifiers/target-related columns.
X_clf = consolidated_df_encoded.drop(columns=[
    'TransactionId', 'UserId', 'AttractionId', 'Rating',
    'VisitYear', 'VisitMonth', 'Trans_date', 'VisitMode',
    'UserContinentId', 'UserRegionId', 'UserCountryId', 'UserCityId',
    'Attraction', 'AttractionAddress', 'AttractionCityId', 'AttractionTypeId',
    'CityCountryId', 'CountryRegionId', 'RegionContinentId'
])
y_clf = consolidated_df_encoded['VisitMode']

# Handle any non-numeric columns that might still be in X_clf
X_clf = X_clf.select_dtypes(include=['number', 'bool'])

# Adjust target variable to be zero-indexed for XGBoost classification
y_clf = y_clf - 1

print(f"Classification Features shape: {X_clf.shape}")
print(f"Classification Target shape: {y_clf.shape}")

# Split data into training and testing sets for classification
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf, test_size=0.2, random_state=42, stratify=y_clf)

print(f"X_train_clf shape: {X_train_clf.shape}")
print(f"X_test_clf shape: {X_test_clf.shape}")
print(f"y_train_clf shape: {y_train_clf.shape}")
print(f"y_test_clf shape: {y_test_clf.shape}")

"""We will use an `XGBClassifier` for this task, as it is a powerful and efficient algorithm for classification problems."""

# Initialize and train the XGBClassifier model
# Use 'objective="multi:softmax"' for multi-class classification and 'num_class' to specify the number of classes.
# The number of classes is the number of unique values in 'VisitMode'.
num_classes = y_clf.nunique()

model_clf = XGBClassifier(
    objective='multi:softmax',
    num_class=num_classes,
    eval_metric='mlogloss',
    use_label_encoder=False, # Suppress warning for deprecated parameter
    random_state=42,
    n_jobs=-1
)

model_clf.fit(X_train_clf, y_train_clf)

print("XGBClassifier model trained successfully.")

"""### Recommendation System: Collaborative Filtering (User-Item Matrix)

We will build a collaborative filtering recommendation system using the `Surprise` library. This system will recommend attractions based on user ratings and preferences by constructing a user-item matrix and applying a Singular Value Decomposition (SVD) algorithm.
"""

import pandas as pd
from surprise import Dataset, Reader
from surprise import SVD
from surprise.model_selection import train_test_split
from surprise import accuracy

# For collaborative filtering, we need UserId, AttractionId, and Rating.
# We will use the original consolidated_df before one-hot encoding for this, to keep the IDs simple.
recommendation_data = consolidated_df[['UserId', 'AttractionId', 'Rating']].copy()

# Define a Reader object for the Surprise library.
# The rating_scale parameter specifies the minimum and maximum possible ratings.
reader = Reader(rating_scale=(1, 5))

# Load the dataset from the DataFrame into a Surprise Dataset object
data = Dataset.load_from_df(recommendation_data[['UserId', 'AttractionId', 'Rating']], reader)

print("Data loaded into Surprise format.")

# Split the data into training and test sets (80/20 split)
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

print(f"Training set size: {trainset.n_users} users, {trainset.n_items} items, {trainset.n_ratings} ratings")
print(f"Test set size: {len(testset)} ratings")

!pip install scikit-surprise

"""We will use the SVD (Singular Value Decomposition) algorithm, a popular model-based collaborative filtering technique, to train our recommendation model."""

# Use the SVD algorithm
algo = SVD(random_state=42, n_epochs=20, lr_all=0.005, reg_all=0.02)

# Train the algorithm on the trainset
algo.fit(trainset)

print("SVD model trained successfully.")

"""Now, let's evaluate the performance of our SVD model on the test set using RMSE and MAE metrics."""

# Make predictions on the testset
predictions = algo.test(testset)

# Then compute RMSE
rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")

"""Finally, let's generate some attraction recommendations for a specific user. We'll pick a user and find attractions they haven't rated yet, then predict ratings for those attractions."""

# Make predictions on the test set
y_pred_clf = model_clf.predict(X_test_clf)

# Evaluate the model
accuracy_clf = accuracy_score(y_test_clf, y_pred_clf)
precision_clf = precision_score(y_test_clf, y_pred_clf, average='weighted') # Use 'weighted' for multi-class
recall_clf = recall_score(y_test_clf, y_pred_clf, average='weighted') # Use 'weighted' for multi-class
f1_clf = f1_score(y_test_clf, y_pred_clf, average='weighted') # Use 'weighted' for multi-class

print(f"XGBoost Classifier Accuracy: {accuracy_clf:.4f}")
print(f"XGBoost Classifier Precision (weighted): {precision_clf:.4f}")
print(f"XGBoost Classifier Recall (weighted): {recall_clf:.4f}")
print(f"XGBoost Classifier F1-Score (weighted): {f1_clf:.4f}")

print("\nClassification Report:")
print(classification_report(y_test_clf, y_pred_clf))

# Get a list of all unique attractions
all_attractions = consolidated_df['AttractionId'].unique()

# Choose a random user to generate recommendations for
user_id = consolidated_df['UserId'].sample(1, random_state=42).iloc[0]
print(f"Generating recommendations for User ID: {user_id}")

# Get the attractions the user has already rated
rated_attractions = recommendation_data[recommendation_data['UserId'] == user_id]['AttractionId'].tolist()

# Filter out attractions the user has already rated
attractions_to_predict = [attraction_id for attraction_id in all_attractions if attraction_id not in rated_attractions]

# Predict ratings for unrated attractions
predicted_ratings = []
for attraction_id in attractions_to_predict:
    # The algo.predict method returns a Prediction object
    prediction = algo.predict(user_id, attraction_id)
    predicted_ratings.append((attraction_id, prediction.est))

# Sort predictions by estimated rating in descending order
predicted_ratings.sort(key=lambda x: x[1], reverse=True)

# Get the top N recommendations (e.g., top 5)
top_n_recommendations = predicted_ratings[:5]

print(f"\nTop 5 recommendations for User {user_id}:")
for attraction_id, estimated_rating in top_n_recommendations:
    # Get attraction name from item_df for better readability
    attraction_name = item_df[item_df['AttractionId'] == attraction_id]['Attraction'].iloc[0]
    print(f"Attraction: {attraction_name} (ID: {attraction_id}), Estimated Rating: {estimated_rating:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# User distribution across continents
continent_counts = consolidated_df['Continent_Name'].value_counts().reset_index()
continent_counts.columns = ['Continent', 'User_Count']

plt.figure(figsize=(10, 6))
sns.barplot(x='Continent', y='User_Count', data=continent_counts, palette='viridis')
plt.title('User Distribution Across Continents')
plt.xlabel('Continent')
plt.ylabel('Number of Users')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# User distribution across regions (top 10 for readability)
region_counts = consolidated_df['Region_Name'].value_counts().head(10).reset_index()
region_counts.columns = ['Region', 'User_Count']

plt.figure(figsize=(12, 6))
sns.barplot(x='Region', y='User_Count', data=region_counts, palette='magma')
plt.title('Top 10 User Distribution Across Regions')
plt.xlabel('Region')
plt.ylabel('Number of Users')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# User distribution across countries (top 10 for readability)
country_counts = consolidated_df['Country_Name'].value_counts().head(10).reset_index()
country_counts.columns = ['Country', 'User_Count']

plt.figure(figsize=(12, 6))
sns.barplot(x='Country', y='User_Count', data=country_counts, palette='cubehelix')
plt.title('Top 10 User Distribution Across Countries')
plt.xlabel('Country')
plt.ylabel('Number of Users')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#### Attraction Types and Popularity based on User Ratings"""

# Calculate average rating per attraction type
attraction_type_popularity = consolidated_df.groupby('AttractionType')['Rating'].mean().sort_values(ascending=False).reset_index()

plt.figure(figsize=(14, 7))
sns.barplot(x='Rating', y='AttractionType', data=attraction_type_popularity, palette='rocket')
plt.title('Average Rating by Attraction Type')
plt.xlabel('Average Rating')
plt.ylabel('Attraction Type')
plt.tight_layout()
plt.show()

"""#### Correlation between VisitMode and User Demographics"""

# Average rating per VisitMode
visit_mode_ratings = consolidated_df.groupby('VisitModeName')['Rating'].mean().sort_values(ascending=False).reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='VisitModeName', y='Rating', data=visit_mode_ratings, palette='crest')
plt.title('Average Rating by Visit Mode')
plt.xlabel('Visit Mode')
plt.ylabel('Average Rating')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Further analysis could involve examining user demographics (e.g., continent, region) by visit mode
# For example, to see if certain visit modes are more prevalent in specific geographic areas.

"""#### Distribution of Ratings Across Different Attractions and Regions"""

# Distribution of ratings for top 10 attractions (based on number of transactions)
top_attractions = consolidated_df_encoded['Attraction'].value_counts().head(10).index
ratings_top_attractions = consolidated_df_encoded[consolidated_df_encoded['Attraction'].isin(top_attractions)]

plt.figure(figsize=(14, 7))
sns.boxplot(x='Attraction', y='Rating', data=ratings_top_attractions, palette='Spectral')
plt.title('Rating Distribution for Top 10 Attractions')
plt.xlabel('Attraction')
plt.ylabel('Rating')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Distribution of ratings across regions (top 5 for readability)
top_regions_for_ratings = consolidated_df['Region_Name'].value_counts().head(5).index
ratings_top_regions = consolidated_df[consolidated_df['Region_Name'].isin(top_regions_for_ratings)]

plt.figure(figsize=(12, 6))
sns.boxplot(x='Region_Name', y='Rating', data=ratings_top_regions, palette='viridis')
plt.title('Rating Distribution Across Top 5 Regions')
plt.xlabel('Region')
plt.ylabel('Rating')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""All specified data preprocessing steps have been performed. The datasets are now cleaner and more consistent for further analysis.

### Model Training: Predicting Ratings

Now, let's train a machine learning model to predict ratings. We will use the `consolidated_df_encoded` DataFrame, which contains all our engineered features. The target variable will be 'Rating'.
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Define features (X) and target (y)
# Drop 'TransactionId', 'UserId', 'AttractionId', 'VisitYear', 'VisitMonth', 'Trans_date' from features as they are either identifiers or already incorporated.
# Also drop 'VisitMode' since 'VisitModeName' encoded versions are used.
X = consolidated_df_encoded.drop(columns=[
    'TransactionId', 'UserId', 'AttractionId', 'Rating',
    'VisitYear', 'VisitMonth', 'Trans_date', 'VisitMode',
    'UserContinentId', 'UserRegionId', 'UserCountryId', 'UserCityId',
    'Attraction', 'AttractionAddress', 'AttractionCityId', 'AttractionTypeId',
    'CityCountryId', 'CountryRegionId', 'RegionContinentId'
])
y = consolidated_df_encoded['Rating']

# Handle any non-numeric columns that might still be in X due to unforeseen issues
X = X.select_dtypes(include=['number', 'bool'])

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""We will use a `RandomForestRegressor` model, which is well-suited for regression tasks and handles various data types well."""

# Initialize and train the RandomForestRegressor model
# Using a small number of estimators for quicker demonstration. For better performance, increase n_estimators.
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

print("RandomForestRegressor model trained successfully.")

"""### Evaluate Rating Prediction Model Performance"""

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5 # Calculate Root Mean Squared Error
r2 = r2_score(y_test, y_pred)

print(f"RandomForestRegressor Mean Absolute Error (MAE): {mae:.4f}")
print(f"RandomForestRegressor Mean Squared Error (MSE): {mse:.4f}")
print(f"RandomForestRegressor Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"RandomForestRegressor R-squared (R2): {r2:.4f}")

import joblib
import pickle

# Define paths for saving artifacts
MODEL_CLF_PATH = '/tmp/xgb_classifier_model.joblib'
SVD_ALGO_PATH = '/tmp/svd_algo.pkl'
CONSOLIDATED_DF_PATH = '/tmp/consolidated_df.pkl'
ITEM_DF_PATH = '/tmp/item_df.pkl'
MODE_DF_PATH = '/tmp/mode_df.pkl'
TYPE_DF_PATH = '/tmp/type_df.pkl'
CITY_DF_PATH = '/tmp/city_df.pkl'
COUNTRY_DF_PATH = '/tmp/country_df.pkl'
REGION_DF_PATH = '/tmp/region_df.pkl'
CONTINENT_DF_PATH = '/tmp/continent_df.pkl'
SCALER_PATH = '/tmp/minmax_scaler.joblib'
CLASSIFICATION_FEATURE_COLUMNS_PATH = '/tmp/classification_feature_columns.pkl'
VISIT_MODE_MAPPING_PATH = '/tmp/visit_mode_mapping.pkl'

# Save the XGBClassifier model
joblib.dump(model_clf, MODEL_CLF_PATH)
print(f"XGBClassifier model saved to {MODEL_CLF_PATH}")

# Save the Surprise SVD algorithm
with open(SVD_ALGO_PATH, 'wb') as f:
    pickle.dump(algo, f)
print(f"Surprise SVD algorithm saved to {SVD_ALGO_PATH}")

# Save dataframes as pickle files to preserve dtypes and structure
consolidated_df.to_pickle(CONSOLIDATED_DF_PATH)
print(f"consolidated_df saved to {CONSOLIDATED_DF_PATH}")
item_df.to_pickle(ITEM_DF_PATH)
print(f"item_df saved to {ITEM_DF_PATH}")
mode_df.to_pickle(MODE_DF_PATH)
print(f"mode_df saved to {MODE_DF_PATH}")
type_df.to_pickle(TYPE_DF_PATH)
print(f"type_df saved to {TYPE_DF_PATH}")
city_df.to_pickle(CITY_DF_PATH)
print(f"city_df saved to {CITY_DF_PATH}")
country_df.to_pickle(COUNTRY_DF_PATH)
print(f"country_df saved to {COUNTRY_DF_PATH}")
region_df.to_pickle(REGION_DF_PATH)
print(f"region_df saved to {REGION_DF_PATH}")
continent_df.to_pickle(CONTINENT_DF_PATH)
print(f"continent_df saved to {CONTINENT_DF_PATH}")

# Save the MinMaxScaler
joblib.dump(scaler, SCALER_PATH)
print(f"MinMaxScaler saved to {SCALER_PATH}")

# Save the exact feature columns used for classification model
with open(CLASSIFICATION_FEATURE_COLUMNS_PATH, 'wb') as f:
    pickle.dump(X_clf.columns.tolist(), f)
print(f"Classification feature columns saved to {CLASSIFICATION_FEATURE_COLUMNS_PATH}")

# Save visit mode mapping (actual names for the predicted numbers)
visit_mode_mapping = dict(zip(y_clf.unique(), mode_df['VisitMode'].iloc[y_clf.unique() + 1].tolist()))
with open(VISIT_MODE_MAPPING_PATH, 'wb') as f:
    pickle.dump(visit_mode_mapping, f)
print(f"Visit mode mapping saved to {VISIT_MODE_MAPPING_PATH}")

"""Now that the necessary models and data have been saved, I will generate the Streamlit application code. This code will create an interactive web application allowing users to input their preferences, get visit mode predictions, receive attraction recommendations, and view relevant data visualizations."""

import streamlit as st
import pandas as pd
import joblib
import pickle
import numpy as np
from surprise import Dataset, Reader
from surprise import SVD
import matplotlib.pyplot as plt
import seaborn as sns

# Define paths for loading artifacts (must match saving paths)
MODEL_CLF_PATH = '/tmp/xgb_classifier_model.joblib'
SVD_ALGO_PATH = '/tmp/svd_algo.pkl'
CONSOLIDATED_DF_PATH = '/tmp/consolidated_df.pkl'
ITEM_DF_PATH = '/tmp/item_df.pkl'
MODE_DF_PATH = '/tmp/mode_df.pkl'
TYPE_DF_PATH = '/tmp/type_df.pkl'
CITY_DF_PATH = '/tmp/city_df.pkl'
COUNTRY_DF_PATH = '/tmp/country_df.pkl'
REGION_DF_PATH = '/tmp/region_df.pkl'
CONTINENT_DF_PATH = '/tmp/continent_df.pkl'
SCALER_PATH = '/tmp/minmax_scaler.joblib'
CLASSIFICATION_FEATURE_COLUMNS_PATH = '/tmp/classification_feature_columns.pkl'
VISIT_MODE_MAPPING_PATH = '/tmp/visit_mode_mapping.pkl'

# --- Load all necessary artifacts ---
@st.cache_resource
def load_artifacts():
    model_clf = joblib.load(MODEL_CLF_PATH)
    with open(SVD_ALGO_PATH, 'rb') as f:
        algo = pickle.load(f)
    consolidated_df = pd.read_pickle(CONSOLIDATED_DF_PATH)
    item_df = pd.read_pickle(ITEM_DF_PATH)
    mode_df = pd.read_pickle(MODE_DF_PATH)
    type_df = pd.read_pickle(TYPE_DF_PATH)
    city_df = pd.read_pickle(CITY_DF_PATH)
    country_df = pd.read_pickle(COUNTRY_DF_PATH)
    region_df = pd.read_pickle(REGION_DF_PATH)
    continent_df = pd.read_pickle(CONTINENT_DF_PATH)
    scaler = joblib.load(SCALER_PATH)
    with open(CLASSIFICATION_FEATURE_COLUMNS_PATH, 'rb') as f:
        classification_feature_columns = pickle.load(f)
    with open(VISIT_MODE_MAPPING_PATH, 'rb') as f:
        visit_mode_mapping = pickle.load(f)

    return (
        model_clf, algo, consolidated_df, item_df, mode_df, type_df,
        city_df, country_df, region_df, continent_df, scaler,
        classification_feature_columns, visit_mode_mapping
    )

(model_clf, algo, consolidated_df, item_df, mode_df, type_df,
 city_df, country_df, region_df, continent_df, scaler,
 classification_feature_columns, visit_mode_mapping) = load_artifacts()

# --- Streamlit App Layout ---
st.title('Travel Recommendation and Visit Mode Prediction App')
st.markdown("""
This application helps predict your likely visit mode based on your preferences
and recommends attractions based on historical data.
""")

# --- Sidebar for User Input ---
st.sidebar.header('Your Preferences')

# Input for Visit Mode Prediction
st.sidebar.subheader('Predict Your Visit Mode')

# Simplified inputs for demonstration
selected_continent_name = st.sidebar.selectbox('Select your Continent', [''] + sorted(consolidated_df['Continent_Name'].unique().tolist()))
selected_region_name = st.sidebar.selectbox('Select your Region', [''] + sorted(consolidated_df['Region_Name'].unique().tolist()))
selected_country_name = st.sidebar.selectbox('Select your Country', [''] + sorted(consolidated_df['Country_Name'].unique().tolist()))
selected_city_name = st.sidebar.selectbox('Select your City', [''] + sorted(consolidated_df['City_Name'].unique().tolist()))

input_visit_year = st.sidebar.slider('Visit Year', min_value=2010, max_value=2023, value=2022)
input_visit_month = st.sidebar.slider('Visit Month', min_value=1, max_value=12, value=10)
input_user_avg_rating = st.sidebar.slider('Average Rating (1-5)', min_value=1.0, max_value=5.0, value=4.0, step=0.1)

# Dropdown for preferred modes for feature aggregation (simplified)
preferred_visit_modes = st.sidebar.multiselect('Preferred Visit Modes (for Avg Rating by Mode feature)', ['Business', 'Couples', 'Family', 'Friends', 'Solo'])

# Predict Visit Mode Button
if st.sidebar.button('Predict Visit Mode'):
    # --- Prepare input for classification model ---
    input_data = pd.DataFrame(0, index=[0], columns=classification_feature_columns)

    # Fill in numerical scaled features (need to unscale/re-scale these properly based on original training data)
    # For simplicity, we use the user input directly, assuming the scaler would handle it
    # In a real app, you'd apply the *inverse* transform to get original scales, then scale the user input.
    # Here, we'll create a dummy array with only the numerical features and scale it.

    numerical_input = np.array([[input_visit_year, input_visit_month, 0, 0, input_user_avg_rating] + [0]*len(preferred_visit_modes)]) # Placeholder values for AttractionCityId, AttractionTypeId for now
    # Find indices for numerical columns within `classification_feature_columns`
    num_cols_in_input = ['VisitYear', 'VisitMonth', 'AttractionCityId', 'AttractionTypeId', 'User_Avg_Rating']
    for mode in ['Business', 'Couples', 'Family', 'Friends', 'Solo']:
        num_cols_in_input.append(f'User_Avg_Rating_Mode_{mode}')

    # Filter to only columns that actually exist in classification_feature_columns
    actual_num_cols_for_model = [col for col in num_cols_in_input if col in classification_feature_columns]

    # Create a dummy numerical input vector for scaling, matching the expected order
    dummy_numerical_values = np.zeros((1, len(actual_num_cols_for_model)))
    dummy_numerical_values[0, actual_num_cols_for_model.index('VisitYear')] = input_visit_year
    dummy_numerical_values[0, actual_num_cols_for_model.index('VisitMonth')] = input_visit_month
    dummy_numerical_values[0, actual_num_cols_for_model.index('User_Avg_Rating')] = input_user_avg_rating

    # For User_Avg_Rating_Mode_*, if selected, set to user's average rating
    for i, mode in enumerate(['Business', 'Couples', 'Family', 'Friends', 'Solo']):
        if f'User_Avg_Rating_Mode_{mode}' in actual_num_cols_for_model and mode in preferred_visit_modes:
             dummy_numerical_values[0, actual_num_cols_for_model.index(f'User_Avg_Rating_Mode_{mode}')] = input_user_avg_rating

    # Scale the dummy numerical input
    scaled_numerical_input = scaler.transform(dummy_numerical_values)

    # Place scaled numerical values into the input_data DataFrame
    for i, col_name in enumerate(actual_num_cols_for_model):
        if col_name in input_data.columns:
            input_data[col_name] = scaled_numerical_input[0, i]

    # Set one-hot encoded categorical features
    if selected_continent_name and f'Continent_Name_{selected_continent_name}' in input_data.columns:
        input_data[f'Continent_Name_{selected_continent_name}'] = 1
    if selected_region_name and f'Region_Name_{selected_region_name}' in input_data.columns:
        input_data[f'Region_Name_{selected_region_name}'] = 1
    if selected_country_name and f'Country_Name_{selected_country_name}' in input_data.columns:
        input_data[f'Country_Name_{selected_country_name}'] = 1
    if selected_city_name and f'City_Name_{selected_city_name}' in input_data.columns:
        input_data[f'City_Name_{selected_city_name}'] = 1

    # Make prediction
    predicted_class = model_clf.predict(input_data)[0]
    predicted_visit_mode = visit_mode_mapping.get(predicted_class, 'Unknown Mode')
    st.sidebar.success(f"Predicted Visit Mode: **{predicted_visit_mode}**")

# Input for Recommendation System
st.sidebar.subheader('Get Attraction Recommendations')
user_id_for_rec = st.sidebar.number_input('Enter User ID for recommendations', min_value=1, value=70456, step=1)

if st.sidebar.button('Get Recommendations'):
    # Get a list of all unique attractions
    all_attractions = consolidated_df['AttractionId'].unique()

    # Get the attractions the user has already rated
    rated_attractions = consolidated_df[consolidated_df['UserId'] == user_id_for_rec]['AttractionId'].tolist()

    # Filter out attractions the user has already rated
    attractions_to_predict = [attraction_id for attraction_id in all_attractions if attraction_id not in rated_attractions]

    # Predict ratings for unrated attractions
    predicted_ratings = []
    for attraction_id in attractions_to_predict:
        prediction = algo.predict(user_id_for_rec, attraction_id) # Using the loaded SVD algo
        predicted_ratings.append((attraction_id, prediction.est))

    # Sort predictions by estimated rating in descending order
    predicted_ratings.sort(key=lambda x: x[1], reverse=True)

    # Get the top N recommendations (e.g., top 5)
    top_n_recommendations = predicted_ratings[:5]

    st.sidebar.write(f"\nTop 5 recommendations for User {user_id_for_rec}:")
    if not top_n_recommendations:
        st.sidebar.info("No new recommendations found for this user or all attractions rated.")
    else:
        for attraction_id, estimated_rating in top_n_recommendations:
            attraction_name = item_df[item_df['AttractionId'] == attraction_id]['Attraction'].iloc[0]
            st.sidebar.write(f"- **{attraction_name}** (Estimated Rating: {estimated_rating:.2f})")

# --- Main Content Area for Visualizations ---
st.header('Data Visualizations')

st.subheader('User Distribution Across Continents')
continent_counts = consolidated_df['Continent_Name'].value_counts().reset_index()
continent_counts.columns = ['Continent', 'User_Count']
fig1, ax1 = plt.subplots(figsize=(10, 6))
sns.barplot(x='Continent', y='User_Count', data=continent_counts, palette='viridis', ax=ax1)
ax1.set_title('User Distribution Across Continents')
ax1.set_xlabel('Continent')
ax1.set_ylabel('Number of Users')
ax1.tick_params(axis='x', rotation=45)
st.pyplot(fig1)

st.subheader('Top 10 User Distribution Across Regions')
region_counts = consolidated_df['Region_Name'].value_counts().head(10).reset_index()
region_counts.columns = ['Region', 'User_Count']
fig2, ax2 = plt.subplots(figsize=(12, 6))
sns.barplot(x='Region', y='User_Count', data=region_counts, palette='magma', ax=ax2)
ax2.set_title('Top 10 User Distribution Across Regions')
ax2.set_xlabel('Region')
ax2.set_ylabel('Number of Users')
ax2.tick_params(axis='x', rotation=45)
st.pyplot(fig2)

st.subheader('Average Rating by Attraction Type')
attraction_type_popularity = consolidated_df.groupby('AttractionType')['Rating'].mean().sort_values(ascending=False).reset_index()
fig3, ax3 = plt.subplots(figsize=(14, 7))
sns.barplot(x='Rating', y='AttractionType', data=attraction_type_popularity, palette='rocket', ax=ax3)
ax3.set_title('Average Rating by Attraction Type')
ax3.set_xlabel('Average Rating')
ax3.set_ylabel('Attraction Type')
st.pyplot(fig3)

st.subheader('Average Rating by Visit Mode')
visit_mode_ratings = consolidated_df.groupby('VisitModeName')['Rating'].mean().sort_values(ascending=False).reset_index()
fig4, ax4 = plt.subplots(figsize=(10, 6))
sns.barplot(x='VisitModeName', y='Rating', data=visit_mode_ratings, palette='crest', ax=ax4)
ax4.set_title('Average Rating by Visit Mode')
ax4.set_xlabel('Visit Mode')
ax4.set_ylabel('Average Rating')
ax4.tick_params(axis='x', rotation=45)
st.pyplot(fig4)

st.subheader('Rating Distribution for Top 10 Attractions')
top_attractions = consolidated_df['Attraction'].value_counts().head(10).index
ratings_top_attractions = consolidated_df[consolidated_df['Attraction'].isin(top_attractions)]
fig5, ax5 = plt.subplots(figsize=(14, 7))
sns.boxplot(x='Attraction', y='Rating', data=ratings_top_attractions, palette='Spectral', ax=ax5)
ax5.set_title('Rating Distribution for Top 10 Attractions')
ax5.set_xlabel('Attraction')
ax5.set_ylabel('Rating')
ax5.tick_params(axis='x', rotation=90)
st.pyplot(fig5)

st.subheader('Rating Distribution Across Top 5 Regions')
top_regions_for_ratings = consolidated_df['Region_Name'].value_counts().head(5).index
ratings_top_regions = consolidated_df[consolidated_df['Region_Name'].isin(top_regions_for_ratings)]
fig6, ax6 = plt.subplots(figsize=(12, 6))
sns.boxplot(x='Region_Name', y='Rating', data=ratings_top_regions, palette='viridis', ax=ax6)
ax6.set_title('Rating Distribution Across Top 5 Regions')
ax6.set_xlabel('Region')
ax6.set_ylabel('Rating')
ax6.tick_params(axis='x', rotation=45)
st.pyplot(fig6)


# To run this Streamlit app, save the code as `app.py` and run `streamlit run app.py` in your terminal.

!pip install streamlit

"""Now that Streamlit is installed, you can re-run the previous cell (`863e8d4b`) to launch the application. Remember that Streamlit applications are typically run from the command line (e.g., `streamlit run app.py`), so you would need to save the code to a file and run it outside of this notebook environment to interact with it fully. This cell only serves to make sure the app code is valid and all dependencies are present."""